### ISSUE TITLE
Please support `-D`/`--chdir`

### ISSUE THREAD

**Issue by joshtriplett** [microsoft/sudo#22]
`sudo` for Linux supports a `-D`/`--chdir` option, which changes to a specified directory before running the specified command. Please consider supporting the same option.

**Comment by zadjii-msft** [comment]
Totally seems reasonable to me. I think this was in the spec originally, just slipped my mind 😅

**Comment by zadjii-msft** [comment]
Something we'll have to keep in mind:

![image](https://github.com/microsoft/sudo/assets/18356694/99650660-a2ea-48a6-886a-5a29f381a2d5)


`-D` combined with `--newWindow` mode will need to do the same thing we do for `-E`, where we launch `sudo` elevated instead of the target app.

**Comment by gerardog** [comment]
> `-D` combined with `--newWindow` mode will need to do the same thing we do for `-E`, where we launch `sudo` elevated instead of the target app.

Wait! This is a problem @zadjii-msft and should be tracked as its own bug !

People may use `newWindow` as a config setting and forget about it... then and occasionally do `sudo notepad.exe ./somefile.txt` or even worse `sudo del ./*.*` expecting to affect the current directory, but hit System32! 

So you could either stop doing `Start-Process -verb RunAs` on the target command, because you can't specify a folder, or you modify a Windows Api.

**Comment by zadjii-msft** [comment]
You know what, we actually did merge this in MSFT:48995647 (internally).
